// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// nec_carrier //
// ----------- //

#define nec_carrier_wrap_target 0
#define nec_carrier_wrap 5

static const uint16_t nec_carrier_program_instructions[] = {
            //     .wrap_target
    0xe035, //  0: set    x, 21                      
    0x20c4, //  1: wait   1 irq, 4                   
    0x0003, //  2: jmp    3                          
    0xe000, //  3: set    pins, 0                    
    0xe001, //  4: set    pins, 1                    
    0x0043, //  5: jmp    x--, 3                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program nec_carrier_program = {
    .instructions = nec_carrier_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config nec_carrier_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + nec_carrier_wrap_target, offset + nec_carrier_wrap);
    return c;
}

    static inline void nec_carrier_program_init(PIO pio, uint sm, uint offset, float clkDiv, uint pin){
        pio_sm_config c = nec_carrier_program_get_default_config(offset);
        sm_config_set_set_pins(&c, pin, 1);
        pio_gpio_init(pio, pin);
        pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
        sm_config_set_clkdiv(&c, clkDiv);
        pio_sm_init(pio, sm, offset, &c);
        pio_sm_set_enabled(pio, sm, true);
    }

#endif
